# Generated by Django 5.2 on 2025-04-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_atributo_categoria_descuento_metodopago_bitacora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacora',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
