# Generated by Django 5.2 on 2025-04-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bitacora_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='usuario',
            field=models.IntegerField(),
        ),
    ]
