# Generated by Django 5.2 on 2025-04-22 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_detallesalida_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atributo',
            old_name='productos',
            new_name='producto',
        ),
    ]
